import MeetupDetails from '../../components/meetups/MeetupDetails';

const MeetupDetailsPage = props => {
  return <MeetupDetails {...props.meetupData} />;
};

// this is necessary if we want to use getStaticProps with dynamic paths
// remember: static HTML needs to be pre-generated by Next.js for every existing dynamic route (at build time!)
// this cannot work without specifying static paths
export async function getStaticPaths() {
  // in reality, the returned paths + params would of course NOT be hardcoded but also fetched from the backend!
  // will do that later
  return {
    // the fallback prop is required and tells Next.js how to handle paths not specified in the list of static paths
    // a value of false means that the static paths are actually all existing paths
    // a value of true means that Next.js will try to generate a dynamic page instead
    // this is useful if we know that there are a few pages that are visited very frequently and don't change much (while others can still be added/removed)
    fallback: false,
    paths: [
      {
        params: {
          meetupId: 'm1',
        },
      },
      {
        params: {
          meetupId: 'm2',
        },
      },
    ],
  };
}

// we can also use the context object available in getStaticProps to access route params!
export async function getStaticProps(context) {
  // this code runs on the server, so you will also only see this log on the server!
  // in development mode, the getStaticProps function runs on every incoming request
  // in the production build, this would not be the case, this function would only be executed in the build step
  console.log(
    'context params of dynamic (but statically generated) meetupId page:',
    context.params
  );

  return {
    props: {
      meetupData: {
        id: 'm1',
        title: 'A First Meetup',
        image:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Stadtbild_M%C3%BCnchen.jpg/1280px-Stadtbild_M%C3%BCnchen.jpg',
        address: 'Some address 5, 12345 Some City',
        description: 'This is a first meetup!',
      },
    },
    revalidate: 60,
  };
}

export default MeetupDetailsPage;
